name: marcelle-newbold
recipe: drupal9
config:
  webroot: web
env_file:
  - default.env
services:
  appserver:
    overrides:
      environment:
        # Support debugging CLI with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando